name: fixyourprint
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bubble: ^1.2.1
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  charts_flutter: ^0.11.0
  cupertino_icons: ^1.0.2
  date_count_down: ^1.0.2
  dio: ^4.0.0
  fl_chart: ^0.40.0
  flutter:
    sdk: flutter
  http: ^0.13.3
  lottie: ^1.1.0
  page_transition: ^2.0.2
  shared_preferences: ^2.0.7
  shimmer: ^2.0.0
  syncfusion_flutter_charts: ^19.3.46
  url_launcher: ^6.0.12
  video_player: ^2.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/login/leafv3.png
    - assets/register/leafv3.png
    - assets/splash/splashscreen1.mp4
    - assets/questions/family.json
    - assets/questions/bus.json
    - assets/questions/car.json
    - assets/questions/flight.json
    - assets/questions/train.json
    - assets/questions/food.json
    - assets/questions/electricity.json 
    - assets/questions/lpg.json 
    - assets/questions/waste.json 

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
